### ISSUE TITLE
Internal Temporary file not writable

### ISSUE THREAD

**Issue by jannkrynauw** [googledatalab/notebooks#94] opened 2017-03-30 15:37 UTC
In the workbook at notebooks/samples/ML Toolbox/Regression/Census/2 Service Preprocess.ipynb the following section:

`analysis_path = os.path.join(workspace_path, 'analysis')
regression.analyze(dataset=train_data, output_dir=analysis_path, cloud=True)`

gives the following error:

> Running numerical analysis...Analyze: failed with error: The internal temporary file is not writable.

**Comment by brandondutra** [comment] 2017-03-30 16:40
@jannkrynauw 
1) Does this script work for you
import tempfile
_, path = tempfile.mkstemp()
print(path)
with open(path, 'w') as f:
  f.write('hello')

new cell: !cat {path}


2) do you get the same problem if you close datalab, restart the container, and run the notebook again?

**Comment by jannkrynauw** [comment] 2017-03-30 17:03
Hi @brandondutra 

The script worked:

<img width="322" alt="screen shot 2017-03-30 at 6 57 59 pm" src="https://cloud.githubusercontent.com/assets/18016598/24516481/13379a1a-157b-11e7-90ca-bbba535636ef.png">

I restarted datalab, as well as installed a fresh new version using the `datalab create ...` command and still get the following error:

> Running numerical analysis...Analyze: failed with error: The internal temporary file is not writable.

**Comment by brandondutra** [comment] 2017-03-30 20:35
I was able to reproduce the error. I'm sorry you had to experience this. 

Just to make sure your error is the same one I am seeing, can you confirm this is failing for you

```
with open('/tmp/hello.txt', 'w') as f:
  f.write('hello')
```

```
IOErrorTraceback (most recent call last)
<ipython-input-49-bdbaa2b614a1> in <module>()
----> 1 with open('/tmp/hello.txt', 'w') as f:
      2   f.write('hello')

IOError: [Errno 2] No such file or directory: '/tmp/hello.txt'
```

**Comment by ojarjur** [comment] 2017-03-30 20:40
@jannkrynauw I think you are hitting a transient (but increasingly reproducible) issue with the Docker volume we use for /tmp.

One workaround that seems (so far) to work is to run:
```shell
datalab stop ${INSTANCE_NAME}
datalab connect ${INSTANCE_NAME}
```

That forces the VM to be stopped and then restarted.

I'm still trying to figure out the root cause, but until we have that (and a fix), try this work-around and see if it helps.

**Comment by ojarjur** [comment] 2017-03-30 21:21
We have a separate tracking issue for this [in the datalab repository](https://github.com/googledatalab/datalab/issues/1263).

That's the right home for it, since it is an issue with the tool rather than one of the notebooks.

As such, I'm going to close this issue and continue the work with updates in that other issue.

**Closed by ojarjur** 2017-03-30 21:21 UTC
